@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "clearCommand\n:Command" as clearCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "undoStack\n:Stack<Command>" as undoStack MODEL_COLOR
end box

[-> LogicManager : execute("clear")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("clear")
activate AddressBookParser

create clearCommand
AddressBookParser -> clearCommand
activate clearCommand

clearCommand --> AddressBookParser
deactivate clearCommand

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> clearCommand : execute(m)
activate clearCommand

clearCommand -> Model : getAddressBook().getPersonList()
activate Model

Model --> clearCommand
deactivate Model

clearCommand -> Model : setAddressBook(new AddressBook())
activate Model

Model --> clearCommand
deactivate Model

create CommandResult
clearCommand -> CommandResult
activate CommandResult

CommandResult --> clearCommand
deactivate CommandResult

clearCommand --> LogicManager
deactivate clearCommand

LogicManager -> clearCommand : isMutable()
activate clearCommand

clearCommand --> LogicManager : true
deactivate clearCommand

opt command is mutable
    LogicManager -> Model : pushMutableCommandHistory(clearCommand)
    activate Model

    Model -> undoStack : push(clearCommand)
    activate undoStack

    undoStack --> Model
    deactivate undoStack

    Model --> LogicManager
    deactivate Model
end

[<-- LogicManager
deactivate LogicManager
@enduml
